name: Maven Build and Goals Display

on:
  push:
    branches:
      - main  # Adjust branch name as per your setup
  pull_request:
    branches:
      - main  # Adjust branch name as per your setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # Specify the Java distribution
        java-version: '11'       # Specify the Java version

    - name: Build Maven Project and Display Goals
      run: |
        mvn clean install -B
        mvn help:describe -Dcmd=clean
        mvn help:describe -Dcmd=compile
        mvn help:describe -Dcmd=test
        mvn help:describe -Dcmd=package
        mvn help:describe -Dcmd=install
        mvn help:describe -Dcmd=deploy
        mvn help:describe -Dcmd=site
        mvn dependency:tree  # Analyze dependencies
        mvn plugin:help      # Display plugin information
